services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
  rabbitmq:
    image: rabbitmq:3.12.6-alpine
    ports:
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      timeout: 5s
      retries: 10
  redis:
    image: redis:7.2.1-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 2s
      retries: 10
  web:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    build: .
    ports:
      - "1323:1323"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: auth
      JWT_ACCESS_TOKEN: secret
      JWT_REFRESH_TOKEN: refresh-secret
      REDIS_ENABLED: 1
      RABBITMQ_ENABLED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
  

