services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
  rabbitmq:
    image: rabbitmq:3.12.6-alpine
    ports:
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      timeout: 5s
      retries: 10
  redis:
    image: redis:7.2.1-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 2s
      retries: 10
  web:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build: .
    ports:
      - "1323:1323"
    env_file:
      - .env
    environment:
      DB_HOST: db
      RABBITMQ_HOST: rabbitmq
  worker:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build:
      context: ./
      dockerfile: ./workers/Dockerfile
    env_file:
      - .env
      - workers/invalidate_refresh_token_family/.env
    environment:
      DB_HOST: db
      RABBITMQ_HOST: rabbitmq

  

