name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'
      - name: Start MySQL
        run: sudo service mysql restart
      - name: Install Redis
        run: sudo apt-get install -y redis-tools redis-server
      - name: Install dependencies
        run: go get .
      - name: Test with the Go CLI
        run: go test ./...
      - name: Build
        run: go build -v ./...
